import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Reservations Page",
    description: "Generated by create next app",
};
function Reservations() {
    return (
        <div>Reservations</div>
    )
}

export default Reservations