import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Cabins Page",
    description: "Generated by create next app",
  };

function Cabins() {
  return (
    <div>Cabins</div>
  )
}

export default Cabins