import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "ID",
    description: "Generated by create next app",
  };
function ID() {
  return (
    <div>ID</div>
  )
}

export default ID