import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Account Page",
    description: "Generated by create next app",
};
function Account() {
    return (
        <div>Account</div>
    )
}

export default Account